version: "3.9"
services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=development
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_URI=postgres://postgres:mysecretpassword@postgres:5432/development?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "sh", "/app/wait-for.sh", "postgres:5432", "--", "sh", "/app/start.sh", "--" ]
    command: [ "/app/main" ]